IgniteUI/igniteui-theming

_index.scss, sass/_index.scss, sass/elevations/_functions.scss, sass/elevations/_index.scss, sass/elevations/_mixins.scss, sass/elevations/presets/_material.scss, test/_elevations.spec.scss, test/_index.scss, test/e2e/theme.scss
=> feat(elevations): add functions and mixins

.github/workflows/npm-publish.yml, .gitignore, package-lock.json, package.json, sass/color/_functions.scss, sass/color/_types.scss, sass/color/presets/dark/_bootstrap.scss, sass/color/presets/dark/_extra.scss, sass/color/presets/dark/_fluent.scss, sass/color/presets/dark/_indigo.scss, sass/color/presets/dark/_material.scss, sass/color/presets/light/_bootstrap.scss, sass/color/presets/light/_extra.scss, sass/color/presets/light/_fluent.scss, sass/color/presets/light/_indigo.scss, sass/color/presets/light/_material.scss, sass/elevations/presets/_material.scss, sass/typography/presets/_bootstrap.scss, sass/typography/presets/_fluent.scss, sass/typography/presets/_indigo.scss, sass/typography/presets/_material.scss, scripts/buildJSON.mjs
=> Translate Sass maps to JSON

sass/themes/_index.scss, sass/themes/charts/_category-chart-theme.scss, sass/themes/charts/_data-chart-theme.scss, sass/themes/charts/_doughnut-chart-theme.scss, sass/themes/charts/_financial-chart-theme.scss, sass/themes/charts/_funnel-chart-theme.scss, sass/themes/charts/_gauge-theme.scss, sass/themes/charts/_geo-map-theme.scss, sass/themes/charts/_graph-theme.scss, sass/themes/charts/_pie-chart-theme.scss, sass/themes/charts/_shape-chart-theme.scss, sass/themes/charts/_sparkline-theme.scss, test/e2e/theme.scss
=> fix(themes): forward chart themes

sass/color/presets/dark/_fluent.scss, sass/color/presets/light/_fluent.scss
=> refactor(fluent): update secondary palette color

sass/color/_functions.scss
=> fix(palettes): missing colors

sass/themes/_functions.scss, test/_themes.spec.scss
=> fix(sizable, pad): compare absolute values

sass/color/_mixins.scss, sass/typography/_mixins.scss, sass/typography/_types.scss, test/_color.spec.scss, test/_typography.spec.scss
=> Change how CSS variables for typography and palettes are generated and included

sass/color/_functions.scss, test/_themes.spec.scss, test/styles/_mocks.scss
=> fix(color): do not check for color validity

sass/themes/schemas/components/light/_grid.scss
Related to IgniteUI/igniteui-angular/issues/13075
=> fix(grid): missing property in schema

sass/themes/schemas/components/light/_icon.scss
related to [#13024](https://github.com/IgniteUI/igniteui-webcomponents/issues/813)
=> refactor(icon): remove size property from icon schema.

sass/themes/schemas/components/light/_avatar.scss, sass/themes/schemas/components/light/_button.scss, sass/themes/schemas/components/light/_chip.scss, sass/themes/schemas/components/light/_drop-down.scss, sass/themes/schemas/components/light/_grid-toolbar.scss, sass/themes/schemas/components/light/_grid.scss, sass/themes/schemas/components/light/_icon.scss, sass/themes/schemas/components/light/_input-group.scss, sass/themes/schemas/components/light/_pagination.scss, sass/themes/schemas/components/light/_tree.scss
=> Adding size inside component schemas

sass/themes/schemas/components/light/_avatar.scss
closes #100
related to https://github.com/IgniteUI/igniteui-webcomponents/issues/856
related to https://github.com/IgniteUI/igniteui-angular/issues/13338
=> refactor(avatar): update border radius value for rounded avatar

sass/themes/schemas/components/light/_icon.scss
=> refactor(icon): change small icon size from 16px to 18px

sass/themes/schemas/components/light/_navdrawer.scss
=> refactor(navdrawer): update indigo schema

sass/themes/schemas/components/light/_grid.scss
Related to IgniteUI/igniteui-angular/issues/13434
=> feat(grid): include styling props for ESF

sass/themes/schemas/components/light/_checkbox.scss
Related to IgniteUI/igniteui-angular/issues/13444
Design handoff:
https://www.figma.com/file/PnlMVPbRLVC2MAMJbebjdh/AppBuilder---Design-System?type=design&node-id=246-15707&mode=design&t=ZchZErIEO2d0B0CT-0
=> fix(checkbox): wrong checked disabled color

sass/themes/_functions.scss, sass/themes/schemas/components/light/_action-strip.scss, sass/themes/schemas/components/light/_button-group.scss, sass/themes/schemas/components/light/_button.scss, sass/themes/schemas/components/light/_calendar.scss, sass/themes/schemas/components/light/_card.scss, sass/themes/schemas/components/light/_carousel.scss, sass/themes/schemas/components/light/_checkbox.scss, sass/themes/schemas/components/light/_chip.scss, sass/themes/schemas/components/light/_dialog.scss, sass/themes/schemas/components/light/_drop-down.scss, sass/themes/schemas/components/light/_expansion-panel.scss, sass/themes/schemas/components/light/_grid.scss, sass/themes/schemas/components/light/_input-group.scss, sass/themes/schemas/components/light/_list.scss, sass/themes/schemas/components/light/_navdrawer.scss, sass/themes/schemas/components/light/_progress.scss, sass/themes/schemas/components/light/_snackbar.scss, sass/themes/schemas/components/light/_splitter.scss, sass/themes/schemas/components/light/_stepper.scss, sass/themes/schemas/components/light/_switch.scss, sass/themes/schemas/components/light/_tabs.scss, sass/themes/schemas/components/light/_time-picker.scss, sass/themes/schemas/components/light/_toast.scss, sass/themes/schemas/components/light/_tooltip.scss, sass/themes/schemas/components/light/_watermark.scss, test/_themes.spec.scss
=> refactor(border-radius): resolve border-radius during schema digestion

sass/themes/schemas/components/dark/_toast.scss, sass/themes/schemas/components/light/_toast.scss
related to https://github.com/IgniteUI/igniteui-webcomponents/issues/916
=> refactor(toast): add border-color

sass/themes/schemas/components/light/_avatar.scss, sass/themes/schemas/components/light/_button-group.scss, sass/themes/schemas/components/light/_button.scss, sass/themes/schemas/components/light/_calendar.scss, sass/themes/schemas/components/light/_card.scss, sass/themes/schemas/components/light/_chip.scss, sass/themes/schemas/components/light/_combo.scss, sass/themes/schemas/components/light/_dialog.scss, sass/themes/schemas/components/light/_drop-down.scss, sass/themes/schemas/components/light/_icon.scss, sass/themes/schemas/components/light/_input-group.scss, sass/themes/schemas/components/light/_list.scss, sass/themes/schemas/components/light/_rating.scss, sass/themes/schemas/components/light/_select.scss, sass/themes/schemas/components/light/_tree.scss
=> feat(schemas): add default size to component schemas

sass/themes/schemas/components/dark/_tree.scss, sass/themes/schemas/components/light/_tree.scss
Closes: #125
Also adding  new color hover-selected-color
=> refactor(tree): change material dark colors

sass/themes/schemas/components/dark/_drop-down.scss, sass/themes/schemas/components/light/_drop-down.scss
Related to IgniteUI/igniteui-webcomponents/issues/994
=> fix(dropdown): items background

sass/themes/schemas/components/dark/_button-group.scss, sass/themes/schemas/components/light/_button-group.scss
Related to IgniteUI/igniteui-webcomponents/issues/1034
=> refactor(btn-group): update fluent colors

sass/themes/schemas/components/dark/_card.scss, sass/themes/schemas/components/light/_card.scss
=> feat(card): implement indigo design changes

sass/themes/schemas/components/dark/_button-group.scss, sass/themes/schemas/components/light/_button-group.scss
=> feat(button-group): implement indigo design changes

sass/themes/schemas/components/dark/_radio.scss, sass/themes/schemas/components/light/_radio.scss
=> feat(radio): update schemas for new indigo ui kit

sass/themes/schemas/components/dark/_banner.scss, sass/themes/schemas/components/light/_banner.scss
=> feat(banner): implement indigo design changes

sass/themes/schemas/components/elevation/_snackbar.scss, sass/themes/schemas/components/light/_snackbar.scss
=> feat(snackbar): implement indigo design changes

.github/workflows/npm-publish.yml, sass/themes/schemas/components/dark/_splitter.scss, sass/themes/schemas/components/light/_splitter.scss
=> feat(splitter): change indigo splitter colors

sass/themes/schemas/components/dark/_slider.scss, sass/themes/schemas/components/light/_slider.scss
Reverts IgniteUI/igniteui-theming#221
=> Revert "feat(slider): update indigo slider schema"

sass/themes/schemas/components/dark/_splitter.scss, sass/themes/schemas/components/light/_splitter.scss
Reverts IgniteUI/igniteui-theming#215
=> Revert "feat(splitter): change indigo splitter colors"

sass/themes/schemas/components/dark/_time-picker.scss, sass/themes/schemas/components/elevation/_time-picker.scss, sass/themes/schemas/components/light/_time-picker.scss
=> Refactor indigo time picker schema

sass/themes/schemas/components/dark/_tree.scss, sass/themes/schemas/components/light/_tree.scss
=> feat(tree): update indigo tree schemas and docs

sass/themes/schemas/components/dark/_calendar.scss, sass/themes/schemas/components/light/_calendar.scss
=> fix(calendar): update indigo colors

sass/typography/presets/_indigo.scss
=> fix(typography): indigo overline styles

sass/color/presets/dark/_indigo.scss, sass/color/presets/light/_indigo.scss
=> fix(indigo-palette): surface color shades

sass/color/presets/dark/_fluent.scss
=> feat(palette): update fluent dark surface color

sass/themes/schemas/components/dark/_switch.scss, sass/themes/schemas/components/light/_switch.scss
=> feat(switch): implement indigo theme updates

sass/themes/schemas/components/dark/_bottom-nav.scss, sass/themes/schemas/components/light/_bottom-nav.scss
=> Bottom nav - update indigo theme

sass/themes/schemas/components/dark/_button-group.scss, sass/themes/schemas/components/dark/_button.scss, sass/themes/schemas/components/dark/_icon-button.scss, sass/themes/schemas/components/light/_button-group.scss, sass/themes/schemas/components/light/_button.scss, sass/themes/schemas/components/light/_icon-button.scss
Related to IgniteUI/igniteui-webcomponents/issues/1107
=> refactor(button/btn-group): color updates

sass/typography/presets/_indigo.scss
Related to https://github.com/IgniteUI/igniteui-angular/pull/14126/
=> feat(typography): update indigo typography overline styles

sass/themes/schemas/components/dark/_switch.scss
related to https://github.com/IgniteUI/igniteui-theming/pull/248
=> feat(switch): update track and border hover colors in dark switch

sass/themes/schemas/components/dark/_progress.scss, sass/themes/schemas/components/light/_progress.scss
=> refactor(progress): update indigo theme styles

sass/themes/schemas/components/dark/_drop-down.scss, sass/themes/schemas/components/elevation/_drop-down.scss, sass/themes/schemas/components/light/_drop-down.scss
=> refactor(drop-down): update indigo styles

sass/elevations/presets/_indigo.scss
Closes #258 
Related to IgniteUI/igniteui-angular/issues/14243
Related to IgniteUI/igniteui-webcomponents/issues/1209
=> refactor(indigo): update elevations presets

sass/themes/schemas/components/dark/_snackbar.scss, sass/themes/schemas/components/elevation/_snackbar.scss
Closes IgniteUI/igniteui-angular/issues/14244
Closes IgniteUI/igniteui-webcomponents/issues/1210
=> refactor(snackbar): indigo theme elevations

sass/themes/schemas/components/dark/_banner.scss, sass/themes/schemas/components/light/_banner.scss
closes https://github.com/IgniteUI/igniteui-webcomponents/issues/1174
=> Banner - update colors according to the new design.

sass/themes/schemas/components/dark/_icon-button.scss, sass/themes/schemas/components/light/_icon-button.scss
Related to IgniteUI/igniteui-angular/issues/14117
Related to IgniteUI/igniteui-webcomponents/issues/1165
=> refactor(icon-button): update component styling

sass/themes/schemas/components/dark/_toast.scss, sass/themes/schemas/components/elevation/_toast.scss, sass/themes/schemas/components/light/_toast.scss
=> refactor(toast): implement indigo design updates

sass/themes/schemas/components/dark/_tooltip.scss, sass/themes/schemas/components/elevation/_tooltip.scss, sass/themes/schemas/components/light/_tooltip.scss
=> refactor(tooltip): indigo design updates

sass/themes/schemas/components/dark/_stepper.scss, sass/themes/schemas/components/light/_stepper.scss
closes https://github.com/IgniteUI/igniteui-theming/issues/277
=> refactor(stepper): update indigo schema colors to match the latest UI kit

sass/themes/schemas/components/dark/_grid-toolbar.scss, sass/themes/schemas/components/light/_grid-toolbar.scss
=> Toolbar - update indigo schema colors to match the latest UI kit

sass/themes/schemas/components/dark/_progress.scss, sass/themes/schemas/components/light/_progress.scss
Related to IgniteUI/igniteui-angular/issues/14350
=> fix(progress): update bootstrap theme colors

sass/themes/schemas/components/dark/_divider.scss
Related to IgniteUI/igniteui-webcomponents/pull/1257
=> fix(divider): dark mode component color

sass/themes/schemas/components/light/_chip.scss
=> fix(chip): indigo theme color issue

sass/themes/schemas/components/dark/_grid-summary.scss, sass/themes/schemas/components/light/_grid-summary.scss, sass/themes/schemas/components/light/_grid.scss
=> feat(grid): indigo design summary updates

sass/themes/schemas/components/dark/_pagination.scss, sass/themes/schemas/components/light/_pagination.scss
=> feat(paginator): implement indigo design changes

sass/themes/schemas/components/dark/_query-builder.scss, sass/themes/schemas/components/light/_grid.scss, sass/themes/schemas/components/light/_query-builder.scss
=> feat(grid): indigo design query builder updates

sass/themes/schemas/components/dark/_carousel.scss, sass/themes/schemas/components/elevation/_carousel.scss, sass/themes/schemas/components/light/_carousel.scss
Related to IgniteUI/igniteui-webcomponents/issues/1226
=> feat(carousel): update with latest changes

sass/themes/schemas/components/dark/_scrollbar.scss, sass/themes/schemas/components/light/_scrollbar.scss
Related to https://github.com/IgniteUI/igniteui-angular/issues/14473
=> refactor(scrollbar): update schemas

sass/themes/schemas/components/light/_progress.scss
Related to IgniteUI/igniteui-angular/issues/14564
=> feat(progress): include circular bar diameter in the schema

sass/themes/schemas/components/dark/_index.scss, sass/themes/schemas/components/dark/_validator.scss, sass/themes/schemas/components/light/_index.scss, sass/themes/schemas/components/light/_validator.scss
related to https://github.com/IgniteUI/igniteui-webcomponents/issues/1195
=> feat(igc-validator): add schemas for validator component

sass/themes/schemas/components/dark/_navbar.scss, sass/themes/schemas/components/light/_navbar.scss
Related https://github.com/IgniteUI/igniteui-angular/issues/14599
=> refactor(navbar): updated colors for material and indigo themes

sass/themes/schemas/charts/light/_data-chart.scss, sass/themes/schemas/components/dark/_calendar.scss, sass/themes/schemas/components/dark/_combo.scss, sass/themes/schemas/components/dark/_grid-summary.scss, sass/themes/schemas/components/dark/_grid-toolbar.scss, sass/themes/schemas/components/dark/_grid.scss, sass/themes/schemas/components/dark/_pagination.scss, sass/themes/schemas/components/dark/_query-builder.scss, sass/themes/schemas/components/dark/_select.scss, sass/themes/schemas/components/elevation/_grid.scss, sass/themes/schemas/components/light/_calendar.scss, sass/themes/schemas/components/light/_combo.scss, sass/themes/schemas/components/light/_grid-summary.scss, sass/themes/schemas/components/light/_grid-toolbar.scss, sass/themes/schemas/components/light/_grid.scss, sass/themes/schemas/components/light/_pagination.scss, sass/themes/schemas/components/light/_query-builder.scss, sass/themes/schemas/components/light/_select.scss, sass/typography/presets/_indigo.scss, scripts/parser.mjs
Closes #279
Closes #301 
Closes #302
=> refactor(themes): indigo-related updates to Grid, Calendar, Combo and Select

sass/themes/schemas/components/dark/_chip.scss, sass/themes/schemas/components/light/_chip.scss
closes #326
related to https://github.com/IgniteUI/igniteui-angular/pull/14790
related to https://github.com/IgniteUI/igniteui-webcomponents/pull/1391
=> Update indigo chip schemas

sass/themes/schemas/components/dark/_tabs.scss, sass/themes/schemas/components/light/_tabs.scss
=> refactor(tabs): indigo design updates

sass/themes/charts/_data-chart-theme.scss, sass/themes/schemas/charts/light/_data-chart.scss
=> refactor(data-chart): add missing theme properties

sass/themes/_functions.scss
=> fix(themes): package will not build with Sass 1.80+

sass/themes/schemas/components/light/_card.scss
=> fix(card): update border radius for card

sass/themes/schemas/components/dark/_time-picker.scss, sass/themes/schemas/components/elevation/_time-picker.scss, sass/themes/schemas/components/light/_time-picker.scss
=> fix(time-picker): visual discrepancies

sass/themes/schemas/components/dark/_tabs.scss, sass/themes/schemas/components/light/_tabs.scss
related to https://github.com/IgniteUI/igniteui-webcomponents/pull/1352
=> refactor(tabs): update schema colors

sass/color/_functions.scss, test/_color.spec.scss
=> fix(color): contrast-color with palette not returning a value of type color

sass/themes/schemas/components/light/_list.scss
Related to IgniteUI/igniteui-angular/issues/15079
=> fix(list): color updates

sass/themes/schemas/components/light/_checkbox.scss
=> fix(checkbox): disabled state tick color

sass/themes/schemas/components/dark/_switch.scss, sass/themes/schemas/components/light/_switch.scss
Related to IgniteUI/igniteui-angular/pull/15269
=> fix(switch): indigo theme invalid state

sass/themes/schemas/components/dark/_grid-summary.scss, sass/themes/schemas/components/dark/_grid.scss, sass/themes/schemas/components/light/_grid-summary.scss, sass/themes/schemas/components/light/_grid.scss
This is only the first step to solving https://github.com/IgniteUI/igniteui-angular/issues/15477. Changes need to be made to the Angular repository as well.
=> refactor(grid): remove summaries properties from grid schema

sass/themes/schemas/components/light/_slider.scss
Closes IgniteUI/igniteui-angular/issues/15567
Closes IgniteUI/igniteui-webcomponents/issues/1616
=> fix(slider): boostrap theme colors

sass/themes/schemas/components/dark/_toast.scss, sass/themes/schemas/components/light/_toast.scss
Closes to https://github.com/orgs/IgniteUI/projects/982/views/1?pane=issue&itemId=100289356&issue=IgniteUI%7Cigniteui-webcomponents%7C1591
Closes to https://github.com/orgs/IgniteUI/projects/982/views/1?pane=issue&itemId=100289382&issue=IgniteUI%7Cigniteui-angular%7C15446
=> refactor(toast): fix toast dicrepancies with UI kits

sass/themes/schemas/components/light/_snackbar.scss
Closes IgniteUI/igniteui-webcomponents/issues/1593
Closes IgniteUI/igniteui-angular/issues/15466
=> fix(snackbar): fluent theme colors

sass/themes/schemas/components/dark/_chip.scss, sass/themes/schemas/components/light/_chip.scss
Related to https://github.com/IgniteUI/igniteui-webcomponents/issues/1602
Related to https://github.com/IgniteUI/igniteui-angular/issues/15502
=> fix(chip): update bootstrap chip schemas

sass/themes/schemas/components/dark/_combo.scss, sass/themes/schemas/components/dark/_input-group.scss, sass/themes/schemas/components/dark/_select.scss, sass/themes/schemas/components/light/_combo.scss, sass/themes/schemas/components/light/_input-group.scss, sass/themes/schemas/components/light/_select.scss
=> fix(inputs): fluent theme discrepancies

sass/themes/schemas/components/dark/_card.scss, sass/themes/schemas/components/light/_card.scss
Related to IgniteUI/igniteui-angular/issues/15598
=> fix(card): color discrepancies with UI kits

sass/themes/schemas/components/light/_rating.scss
Related to IgniteUI/igniteui-webcomponents#1655
=> refactor(rating): move symbol size to schema

sass/themes/schemas/components/dark/_drop-down.scss, sass/themes/schemas/components/light/_drop-down.scss
Closes #412 
Closes IgniteUI/igniteui-webcomponents/issues/1649
=> refactor(dropdown): color discrepancies with UI kits

sass/themes/schemas/components/dark/_label.scss, sass/themes/schemas/components/light/_label.scss
Related to IgniteUI/igniteui-angular/issues/15554
=> refactor(label): update colors

sass/themes/schemas/components/light/_stepper.scss
=> feat(stepper): update hover/focus states background

sass/themes/schemas/components/dark/_progress.scss
=> feat(progress): update dark base colors for track and circle

sass/themes/schemas/components/dark/_avatar.scss, sass/themes/schemas/components/light/_avatar.scss
=> refactor(avatar): update dark background

sass/themes/schemas/components/dark/_date-range-picker.scss, sass/themes/schemas/components/light/_date-range-picker.scss
Related to IgniteUI/igniteui-webcomponents/issues/1596
=> refactor(date-range-picker): latest design changes

sass/themes/schemas/components/dark/_date-picker.scss
Related to [this issue](https://github.com/issues/assigned?issue=IgniteUI%7Cigniteui-theming%7C440)
=> fix(datepicker): change meta variant in dark schema

sass/themes/schemas/components/dark/_dialog.scss
=> fix(dialog): change border color in Bootstrap dark
